version: "3.7"

services:
  application:
    container_name: app
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=makeUrTasks
      - DB_USER=root
      - DB_PASSWORD=root
    networks:
      - app_network

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

volumes:
  mysql_data:

networks:
  app_network:
